# Generated by Django 3.2.6 on 2023-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_users_appusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appusers',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
