# Generated by Django 4.2.4 on 2023-09-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
