# Generated by Django 4.2.4 on 2023-09-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_userprofile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
