# Generated by Django 4.2.4 on 2023-09-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/'),
        ),
    ]
